source 'https://rubygems.org'

gem "nanoc", "~> 4.0"
gem "adsf"
gem "guard-nanoc"
gem "guard-livereload"
gem "guard-bundler"
gem "guard-pow"
gem "coderay"
gem "kramdown"
gem "pygments.rb"
gem "nokogiri"
gem 'uglifier'
gem 'sass'
gem 'coffee-script'
gem 'nanoc-sprockets3'
gem "bootstrap-bookingsync-sass"
